# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - fitconnect-network

  backend:
    image: fitconnect-backend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - fitconnect-network

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=fitconnect
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitconnect-network

  redis:
    image: redis:7-alpine
    networks:
      - fitconnect-network

networks:
  fitconnect-network:
    driver: bridge

volumes:
  postgres_data:
